### ISSUE TITLE
MBP 13,1 - Integrated Intel Graphics Card - Heavy TTY glitches when KMS is enabled.

### ISSUE THREAD

**Issue by 0x0f0f0f** [Dunedan/mbp-2016-linux#76] opened 2018-09-19 06:21 UTC
This happens on ubuntu 18.10, void linux and alpine linux. The only way to stop the [glitches](https://i.imgur.com/NiSIN7N.jpg) is to start the kernel with nomodeset. X11 crashes when modeset is disabled.

This makes me able to boot only on TTYs or on auto-starting X11 distros.

**Comment by roadrunner2** [comment] 2018-09-19 06:55
Does adding `i915.fastboot=1` to your kernel command line help?

**Comment by 0x0f0f0f** [comment] 2018-09-24 08:02
Doesn't help at all. Still glitched.

**Comment by Dunedan** [comment] 2018-09-27 09:17
I get the same glitches until plymouth takes over. Started several months ago (if not longer). Not sure what's causing them, but so far it hasn't been an issue for me, because once plymouth takes over everything is fine. Maybe related to KMS?

**Comment by roadrunner2** [comment] 2018-10-05 11:00
I narrowed this down to commit torvalds/linux@011f22eb545a35f972036bb6a245c95c2e7e15a0 introduced in 4.18-rc1, at least for the MBP13,3 - try reverting it and see if it fixes the issue for 13,1 too.

**Comment by Dunedan** [comment] 2018-10-05 15:48
Oh the irony: Instead of progressing towards flicker-free boot, as intended by this commit, it causes garbled output for us. :smile:

**Comment by zprogd** [comment] 2018-10-05 22:22
Revert fixes it also for 14.1

**Comment by 0x0f0f0f** [comment] 2018-10-06 09:13
Has anybody filed an issue in [torvalds/linux](github.com/torvalds/linux) yet?

**Comment by cyrusmg** [comment] 2018-10-12 10:34
Does this imply https://github.com/Dunedan/mbp-2016-linux/issues/62 is not a problem anymore ?

**Comment by Dunedan** [comment] 2018-10-12 19:27
@cyrusmg Unfortunately I don't think so, as the commit in question got introduced in Linux 4.18-rc1, while the problem discussed in #62 already exists since Linux 4.17. Nevertheless if you got a MacBookPro13,1 or MacBookPro14,1 it could be worth trying to run a kernel without that patch and see if it changes anything.

**Comment by 0x0f0f0f** [comment] 2018-10-19 08:45
https://bugs.freedesktop.org/show_bug.cgi?id=108264

fixed in drm-tip commit `914a4fd8cd28016038ce749a818a836124a8d270`

**Comment by 0x0f0f0f** [comment] 2018-10-19 08:46
Let's see if we can get this upstreamed into a kernel RC

**Comment by roadrunner2** [comment] 2018-11-27 09:44
FYI, the fix is in 4.20-rc1.

**Comment by Dunedan** [comment] 2018-12-28 21:37
I can confirm that this is fixed in 4.20 and I'm therefore closing this issue. Thanks @roadrunner2 for taking care of this issue.

**Closed by Dunedan** 2018-12-28 21:37 UTC
